BOOT:	EQU BIOS_START
WBOOT:	EQU BIOS_START + 3
CONST:	EQU BIOS_START + 6
CONIN:	EQU BIOS_START + 9
CONOUT:	EQU BIOS_START + 12
LIST:	EQU BIOS_START + 15
PUNCH:	EQU BIOS_START + 18
READER:	EQU BIOS_START + 21
HOME:	EQU BIOS_START + 24
SELDSK:	EQU BIOS_START + 27
SETTRK:	EQU BIOS_START + 30
SETSEC:	EQU BIOS_START + 33
SETDMA:	EQU BIOS_START + 36
READ:	EQU BIOS_START + 39
WRITE:	EQU BIOS_START + 42
PRSTAT:	EQU BIOS_START + 45
SECTRN:	EQU BIOS_START + 48
